"""One play-through: the hero, and the fight he is in the middle of.

The second thing this application stores, and the first that is *state* rather
than a trace. The book stays on disk and the reading history stays a log; a game
is the only document that is read, changed and written back.

The id is a `uuid4().hex` this app generates rather than Mongo's ObjectId,
because it travels in the session cookie.

The hero is stored flat rather than as an embedded document: there is exactly one
per game, and `vie_actuelle` is written after every assault, which is cheaper and
plainer as a top-level field. `combat` is embedded and unset between fights —
absent means the hero is reading, not fighting.
"""

from mongoengine import (
    BooleanField,
    DateTimeField,
    Document,
    EmbeddedDocument,
    EmbeddedDocumentField,
    EmbeddedDocumentListField,
    IntField,
    ListField,
    StringField,
)


class GameExchange(EmbeddedDocument):
    """What happened between the hero and one adversary in one assault."""

    meta = {"strict": False}

    enemy_name = StringField()
    enemy_force = IntField()
    enemy_dice = ListField(IntField())
    enemy_attack_force = IntField()
    # "hero", "enemy", or unset when the two Forces d'Attaque were equal.
    winner = StringField()
    damage = IntField(default=0)
    divine_judgement = BooleanField(default=False)


class GameAssault(EmbeddedDocument):
    """One assault: the hero's single roll, and every exchange it settled."""

    meta = {"strict": False}

    number = IntField()
    hero_dice = ListField(IntField())
    hero_attack_force = IntField()
    exchanges = EmbeddedDocumentListField(GameExchange)


class GameItem(EmbeddedDocument):
    """One thing in the hero's bag, and how many of it he has."""

    meta = {"strict": False}

    element = StringField(required=True)
    label = StringField(required=True)
    count = IntField(required=True)


class PendingChange(EmbeddedDocument):
    """A gain or loss only the reader can decide on.

    Its condition is free French — a prerequisite or a duration — or its amount
    is one the page's text asks to be rolled. Either way it waits here until the
    reader applies it or waves it away.
    """

    meta = {"strict": False}

    element = StringField(required=True)
    label = StringField(required=True)
    amount = IntField()
    condition = StringField()
    note = StringField()
    # 1 for a gain, -1 for a loss.
    sign = IntField(default=1)
    # The page whose choice carried it, so the reader can see where it came from.
    page = StringField()


class GameEnemy(EmbeddedDocument):
    """One adversary of the current fight, as it stands."""

    meta = {"strict": False}

    name = StringField()
    force = IntField()
    vie_max = IntField()
    vie_actuelle = IntField()
    damage_adjustment = IntField(default=0)


class GameCombat(EmbeddedDocument):
    """The fight the hero is in, and everything it has cost so far."""

    meta = {"strict": False}

    # The page the fight was started from, which is where its outcome branches.
    page = StringField()
    fight_type = StringField()
    enemies = EmbeddedDocumentListField(GameEnemy)
    assaults = EmbeddedDocumentListField(GameAssault)
    status = StringField()

    # Where the book sends the hero next. `on_defeat` is a page number or the
    # string "death"; either can be unset when the parser found no branch.
    on_victory = StringField()
    on_defeat = StringField()
    on_flee = StringField()

    # Whether the page's text adds a rule the engine does not implement, so a
    # reader is told rather than quietly given a wrong fight.
    has_special_rules = BooleanField(default=False)


class Game(Document):
    """A hero, rolled once, and the fight he is in the middle of."""

    meta = {
        "collection": "games",
        "indexes": ["book"],
        "strict": False,
    }

    # Generated by core.db.start_game(); see the module docstring.
    id = StringField(primary_key=True)
    book = StringField(required=True)

    # Which set of rules rolled this hero up — "normal" or "easy". Kept so the
    # sheet can print the throw that made him, and so a game says how it was
    # played.
    mode = StringField(required=True)

    force = IntField(required=True)
    vie_max = IntField(required=True)
    vie_actuelle = IntField(required=True)

    # The two throws that made the hero, kept so the sheet can show its work:
    # "Force : 3 + 2 (2D6) + 6 = 11".
    force_dice = ListField(IntField())
    vie_dice = ListField(IntField())

    # "vous êtes équipé de votre épée et d'un sac", "4 rations de provisions",
    # and a purse of two throws of two dice.
    gold = IntField(default=0)
    gold_dice = ListField(IntField())
    items = EmbeddedDocumentListField(GameItem)

    # Changes waiting on the reader's word; see PendingChange.
    pending = EmbeddedDocumentListField(PendingChange)

    combat = EmbeddedDocumentField(GameCombat)
    created_at = DateTimeField()

    # When the hero's Vie reached zero, and where. Unset while he lives, which
    # is what tells a game apart from an epitaph: a hero abandoned in good
    # health is simply left behind, and does not join the fallen.
    died_at = DateTimeField()
    died_on_page = StringField()
    died_of = StringField()

    @property
    def is_dead(self) -> bool:
        """Whether this hero has already been laid to rest."""
        return self.died_at is not None

    def __str__(self) -> str:
        state = "mort" if self.is_dead else f"Vie {self.vie_actuelle}/{self.vie_max}"
        return f"{self.book} ({self.mode}) — Force {self.force}, {state}"
