"""One play-through: the hero, and the fight he is in the middle of.

The second thing this application stores, and the first that is *state* rather
than a trace. The book stays on disk and the reading history stays a log; a game
is the only row that is read, changed and written back.

The id is a `uuid4().hex` this app generates rather than an autoincrement,
because it travels in the session cookie.

Three real columns: the id, the book every query is scoped to, and `died_at`,
which the memorial filters and sorts on. **Everything else is in the blob** —
the hero's characteristics and dice, his purse and bag, the changes waiting on
the reader, the open fight, and where and of what he died:

    mode            "normal" or "easy" — which set of rules rolled him up
    force, vie_max, vie_actuelle
    force_dice, vie_dice        the throws that made him, for the sheet
    gold, gold_dice
    items           [{element, label, count}]
    pending         [{element, label, amount, condition, note, sign, page}]
    combat          None while he is reading, or {page, fight_type, status,
                    on_victory, on_defeat, on_flee, has_special_rules,
                    enemies: [{name, force, vie_max, vie_actuelle,
                    damage_adjustment}], assaults: [{number, hero_dice,
                    hero_attack_force, exchanges: [{enemy_name, enemy_force,
                    enemy_dice, enemy_attack_force, winner, damage,
                    divine_judgement}]}]}
    created_at      ISO 8601 text
    died_on_page, died_of       set with `died_at`, see below

`died_at` is unset while he lives, which is what tells a game apart from an
epitaph: a hero abandoned in good health is simply left behind, and does not
join the fallen.
"""

from datetime import datetime

from sqlalchemy import Index, String
from sqlalchemy.orm import Mapped, mapped_column

from haute_tension.core.models.base import Base
from haute_tension.core.models.hybrid_document import HybridDocument
from haute_tension.core.models.utc_datetime import UtcDateTime


class Game(HybridDocument, Base):
    """A hero, rolled once, and the fight he is in the middle of."""

    __tablename__ = "games"
    __table_args__ = (
        # The memorial: the fallen of one book, most recent first.
        Index("ix_games_book_died_at", "book", "died_at"),
    )

    # Generated by core.db.start_game(); see the module docstring.
    id: Mapped[str] = mapped_column(String(32), primary_key=True)
    book: Mapped[str] = mapped_column(String, nullable=False, index=True)
    died_at: Mapped[datetime | None] = mapped_column(UtcDateTime)

    @property
    def is_dead(self) -> bool:
        """Whether this hero has already been laid to rest."""
        return self.died_at is not None

    def __str__(self) -> str:
        hero = self.to_dict()
        state = (
            "mort"
            if self.is_dead
            else f"Vie {hero.get('vie_actuelle')}/{hero.get('vie_max')}"
        )
        return f"{self.book} ({hero.get('mode')}) — Force {hero.get('force')}, {state}"
